Make sure that all tests pass if qt sub-directories are removed, and Qt is not installed

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -88,6 +88,12 @@ matrix:
         - os: linux
           env: PYTHON_VERSION=2.7 ASTROPY_VERSION=1.0 QT_PKG=pyside
 
+        # Test without any Qt installation, which will also cause all qt
+        # sub-directories to be removed, to make sure that no non-Qt code has
+        # any dependence on Qt code.
+        - os: linux
+          env: PYTHON_VERSION=2.7 QT_PKG=False
+
     allow_failures:
       - env: PYTHON_VERSION=2.7 ASTROPY_VERSION=1.0 QT_PKG=pyside
 
@@ -97,7 +103,7 @@ before_install:
   - if [[ $QT_PKG == pyqt5 ]]; then export CONDA_CHANNELS="astropy-ci-extras astrofrog"; fi
 
   # Prepare dependency list
-  - export CONDA_DEPENDENCIES="$QT_PKG "$CONDA_DEPENDENCIES
+  - if [[ $QT_PKG != False ]]; then export CONDA_DEPENDENCIES="$QT_PKG "$CONDA_DEPENDENCIES; fi
 
   # Special cases depending on IPython version
   - if [[ $IPYTHON_VERSION == 4 ]]; then export CONDA_DEPENDENCIES="qtconsole ipykernel "$CONDA_DEPENDENCIES; fi
@@ -134,15 +140,27 @@ install:
       export QT_DEBUG_PLUGINS=1;
     fi
 
+  # Uninstall any version of Qt if QT_PKG is False, and remove all qt
+  # sub-directories
+  - if [[ $QT_PKG == False ]]; then
+      conda remove pyqt || true;
+      conda remove pyside || true;
+      conda remove pyqt5 || true;
+      conda remove qt || true;
+      conda remove qt5 || true;
+      find . -name "qt" -type d -exec rm -r {} \; || true;
+    fi
+
   # We need to install glue in order to make sure that the entry points are
   # installed
   - python setup.py install
 
 script:
+
   - python setup.py test -a "$PYTEST_ARGS";
 
-  # In the following, we use separate if statements for each line, to make 
-  # sure the exit code from each one is taken into account for the overall 
+  # In the following, we use separate if statements for each line, to make
+  # sure the exit code from each one is taken into account for the overall
   # exit code.
   - if [ $DOC_TRIGGER ]; then cd doc; make html 2> warnings.log; cd ..; fi
   - if [ $DOC_TRIGGER ]; then cat doc/warnings.log; fi
